### PR TITLE
article on wave sort

### LINKED ISSUE #488: Content: Wave sort
## 📚 Documentation

Given an unsorted array. Sort the array in such a way that the array looks like a wave array.
For example, if the given sequence arr has n elements then the sorted wave array looks like -
arr[0] >= arr[1] and arr[1] <= arr[2]
arr[2] >= arr[3] and arr[3] <= arr[4]
arr[4] >= arr[5] and arr[5] <= arr[6] And so on
For example, the given array : arr = { 4, 3, 5, 2, 3, 1, 2 } 
The above figure is a visual representation of the given arr and you can see we can express ‘arr’ in a waveform array because 
4>3 and 3<5 
5>2 and 2<3
3>1 and 1<2
And it follows the condition of wave array.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by gayatri517**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Both codes in C++ and python are written by me

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #488

### CODE REVIEW

**Comment by gayatri517** [comment]
Please review my PR @iamrajiv @atarax665 @gat786 @nidh-ish
Thank you

**Comment by gayatri517** [comment]
Please review my PR @iamrajiv @atarax665 @gat786 @nidh-ish
Thank you

**Comment by gayatri517** [comment]
Please review my PR  @iamrajiv @ankitaggarwal23 @atarax665 @gat786 @nidh-ish @siddharth25pandey @bhav09 
Thank you

**Comment by gayatri517** [comment]
@atarax665 please review my PR

**Review by iamrajiv — APPROVED** [review]

**Review by siddharth25pandey — APPROVED** [review]
@gayatri517 LGTM 💯 Able to mege

**Pull request merged**
