### PR TITLE
Added Documentation for Identical Binary Tree

### PR DESCRIPTION
**Pull request by Saatvik21**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

`Yes`

### Description

I've added an article to check whether the two trees are identical or not. I've also refactored both codes to match accordingly.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #502

### CODE REVIEW

**Comment by Saatvik21** [comment]
Please review @atarax665 @iamrajiv @bhav09 @ankitaggarwal23

**Review by iamrajiv — APPROVED** [review]

**Review by siddharth25pandey — APPROVED** [review]
@Saatvik21 LGTM 💯 Able to merge

**Comment by siddharth25pandey** [comment]
@Saatvik21 Resolve the merge Conflicts

**Comment by Saatvik21** [comment]
> @Saatvik21 Resolve the merge Conflicts

@siddharth25pandey Done!

**Review by atarax665 — APPROVED** [review]

**Comment by Saatvik21** [comment]
@atarax665 please add the level label as well.

**Pull request merged**
