### PR TITLE
Added Documentation for Auto Key Cipher

### LINKED ISSUE #481: Auto key Cipher Documentation
## 📚 Documentation

(A clear and concise description of what the issue is.)

I would like to write a documentation on Autokey cipher algorithm about how it works and it's functionality...etc
Discussing the complexity of the algorithm and few other related things.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

### PR DESCRIPTION
**Pull request by ravireddy07**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

`Yes`

### Description

Added Documentation for Auto Key Cipher Algorithm and added code in C++ and Java.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #481

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
Thank you for your valuable time.😊

**Comment by ravireddy07** [comment]
@ankitaggarwal23  Can I know the reason..?

**Comment by ankitaggarwal23** [comment]
You don't even tag any of the mentors for review and at the end, you are saying for review. The mistake is from your side. GSSoc period is now over. Also, you created an issue on your own not even a single mentor assigns you for that issue. Strictly against the guidelines. I will review. Because that is unfair to others.

**Review by ankitaggarwal23 — APPROVED** [review]

**Comment by ravireddy07** [comment]
Thanks for the review. @ankitaggarwal23 
Just would like to mention that i'm not contributing as a part of GSSOC. It's a normal contribution.

**Pull request merged**
