### PR TITLE
Article on print all permutations

### PR DESCRIPTION
**Pull request by gayatri517**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Both codes in python and C++ are written by me

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #513

### CODE REVIEW

**Comment by gayatri517** [comment]
@atarax665 @siddharth25pandey Kindly review my PR.
Thank you

**Comment by siddharth25pandey** [comment]
@gayatri517 Also the Resolve the merge conflicts

**Comment by gayatri517** [comment]
@siddharth25pandey I have made the changes and resolved the conflicts.
Kindly review

**Review by siddharth25pandey — APPROVED** [review]
@gayatri517 LGTM 💯 Able to merge

**Pull request merged**
