### PR TITLE
Added Extended Euclidean Algorithm doc

### LINKED ISSUE #111: Content: Extended Euclidean Algorithm
## Description

Add the article for Extended Euclidean Algorithm. Use the following structure: 
- Introduction
- Explanation
- Algorithm
- Code
- Sample I/O
- Complexity Analysis

### PR DESCRIPTION
**Pull request by nagasrihith608**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description
Added Extended Euclidean Algorithm doc
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixed #111 
(Write your answer here.)

### CODE REVIEW

**Comment by nagasrihith608** [comment]
@HarshCasper, @ankitaggarwal23  please have a look into this pr. Thank You!

**Comment by nagasrihith608** [comment]
@anushkrishnav please suggest changes if any. Thank you!

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Can you please add the changes on the `sidebars.js` so that I can see them on a live web view?

**Comment by nagasrihith608** [comment]
@HarshCasper can you help me in solving this error. I am not able to understand what went wrong.

**Comment by nagasrihith608** [comment]
> Can you please add the changes on the `sidebars.js` so that I can see them on a live web view?

please look into this now I had made suggested changes

**Comment by HarshCasper** [comment]
> > Can you please add the changes on the `sidebars.js` so that I can see them on a live web view?
> 
> please look into this now I had made suggested changes

Please solve the merge conflicts and I would approve it then 😄

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
