### PR TITLE
DFS

### PR DESCRIPTION
**Pull request by SalmaZakaria**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

DFS Algorithm for traversing a graph

### Checklist

- [YES] I've read the contribution guidelines.
- [YES] I've checked the issue list before deciding what to submit.
- [YES] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#61

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
Thank you for your valuable time.😊

**Comment by SalmaZakaria** [comment]
@ankitaggarwal23 Why you close it without merging?

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 Why you close it without merging?

The time is Up? You didn't even tag anyone of the mentor for review. How will come to know about it for review.

**Review by ankitaggarwal23 — COMMENTED** [review]
Code already present #402

**Pull request closed without merging**
