### PR TITLE
adding matrix transpose

### PR DESCRIPTION
**Pull request by aaadddiii**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

adding documentation for matrix transpose

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #34

### CODE REVIEW

**Comment by aaadddiii** [comment]
@HarshCasper  can you please review and merge my pr

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Make the same changes here: https://github.com/TesseractCoding/NeoAlgo-Docs/pull/164#pullrequestreview-633034477

**Comment by aaadddiii** [comment]
@HarshCasper  I have made the changes can you please review my pr

**Comment by aaadddiii** [comment]
@HarshCasper  I have made the changes , please review it

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
