### PR TITLE
Next prime number

### LINKED ISSUE #276: Next prime number
## 📚 Documentation
An article for finding the next prime number from the given number.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by tanvi355**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added an article on finding the next prime number of a given number.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #276

### CODE REVIEW

**Comment by tanvi355** [comment]
@HarshCasper @iamrajiv @ankitaggarwal23 please review the PR.

**Comment by tanvi355** [comment]
@HarshCasper @iamrajiv @ankitaggarwal23 please review the PR.

**Review by iamrajiv — APPROVED** [review]

**Comment by tanvi355** [comment]
@atarax665, please review the PR.

**Review by ankitaggarwal23 — APPROVED** [review]
LGTM💯

**Pull request merged**
