### PR TITLE
Row with Max 1's

### LINKED ISSUE #347: Row with max 1's in a matrix
## 🚀 Feature

A article on row with maximum 1 in a matrix

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by tk315**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

# Code in both C++ and Python is written by me.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #347

### CODE REVIEW

**Comment by tk315** [comment]
Please review sir @HarshCasper @iamrajiv @ankitaggarwal23 @atarax665 @gat786 @nidh-ish

**Review by iamrajiv — APPROVED** [review]

**Comment by tk315** [comment]
@HarshCasper Build done successfully

**Comment by tk315** [comment]
@vybhav72954 please review

**Comment by tk315** [comment]
@siddharth25pandey please review

**Comment by tk315** [comment]
@atarax665 please review

**Review by atarax665 — APPROVED** [review]

**Comment by atarax665** [comment]
Resolve conflict.

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
