### PR TITLE
Fractional knapsack

### PR DESCRIPTION
**Pull request by Amit366**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added documentation for Fractional kanpsack

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #182

### CODE REVIEW

**Comment by Amit366** [comment]
@HarshCasper please review.

**Comment by Amit366** [comment]
@iamrajiv please review

**Review by iamrajiv — APPROVED** [review]

**Comment by Amit366** [comment]
@atarax665 please review

**Comment by Amit366** [comment]
@ankitaggarwal23 @atarax665 please review

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
