### PR TITLE
fcfs cpu algorithm

### LINKED ISSUE #97: Content: CPU Scheduling Algorithm - FCFS
## Description

Add the article for FCFS Scheduling algorithm. Use the following structure: 
- Introduction
- Explanation
- Algorithm
- Code
- Sample I/O
- Complexity Analysis

### PR DESCRIPTION
**Pull request by nagasaisriya**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Added documentation for FCFS CPU Scheduling algorithm
(Write your answer here.)

### Checklist

- [ x ] I've read the contribution guidelines.
- [ x ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes  #97 
(Write your answer here.)

### CODE REVIEW

**Comment by vybhav72954** [comment]
Link the issue properly, Use `#Fixes`

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Add the articles to `sidebars.js`. Without the same, I would not be able to review your article.

**Comment by nagasaisriya** [comment]
> Add the articles to `sidebars.js`. Without the same, I would not be able to review your article.

Okay

**Comment by nagasaisriya** [comment]
Hey @HarshCasper I've added the article to sidebar and made changes, do review it. Thank you.

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity since last 21 days. Thank you for your valuable time.😊

**Pull request closed without merging**
