### PR TITLE
Made text become dark on hovering for readability

### LINKED ISSUE #62: The text on Get Started Button on Homepage becomes illegible on hovering
## 🐛 Bug Report

On hovering, the background color of the button becomes nearly identical to the text color, hampering readability

### Have you read the [Contributing Guidelines on Pull Requests]
yes

### PR DESCRIPTION
**Pull request by N-Shar-ma**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Made the color of the text on the get Started Button become a dark grey, instead of remaining white, on hovering, so that there is sufficient contrast between it and the pale white background color

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Closes #62

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Can we keep the current styling as it is, and change the text and background color to have sufficient contrast? It would need to be achieved by adding some CSS code in the proprietary CSS module instead of inline. 

Let me know if that's feasible.

**Comment by N-Shar-ma** [comment]
@HarshCasper Do you mean I should add a class for this button in the style.module,css, in which I define it's color and background color properties to override the defaults? 
I can do that, but please let me know what exact colors should I use, since the defaults already have sufficient contrast. It was the inline style, that I removed in the last commit, that was causing low contrast

**Comment by HarshCasper** [comment]
> @HarshCasper Do you mean I should add a class for this button in the style.module,css, in which I define it's color and background color properties to override the defaults?
> I can do that, but please let me know what exact colors should I use, since the defaults already have sufficient contrast. It was the inline style, that I removed in the last commit, that was causing low contrast

Yes. Your reasoning is correct. That is why I labelled it as `Level2`. 

You can use the existing colors as the original while for hover you can use white as the background color and black as the text color. Let me know if that's feasible.

**Comment by N-Shar-ma** [comment]
> > @HarshCasper Do you mean I should add a class for this button in the style.module,css, in which I define it's color and background color properties to override the defaults?
> > I can do that, but please let me know what exact colors should I use, since the defaults already have sufficient contrast. It was the inline style, that I removed in the last commit, that was causing low contrast
> 
> Yes. Your reasoning is correct. That is why I labelled it as `Level2`.
> 
> You can use the existing colors as the original while for hover you can use white as the background color and black as the text color. Let me know if that's feasible.

Sure, I will make these changes by today evening. Thanks for the quick reply!

**Review by HarshCasper — CHANGES_REQUESTED** [review]
It does not provide the desired change as of now. We want the background color to be blue and the text color to be white.

When someone hovers on it, we should have text color as black and background color as white.

**Comment by N-Shar-ma** [comment]
Got it, I'm sorry I only checked in dark mode and not light mode where this unwanted behavior happens. Will make the corrections immediately

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
Wonderful work! 

We will look forward for more of your contributions :rocket:

**Pull request merged**
