### PR TITLE
searching in matrix 

### LINKED ISSUE #345: Search in a Matrix
## 🚀 Feature

An article on Search in a matrix

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by tk315**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

# Both the codes in C++ and Python are written by me.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #345

### CODE REVIEW

**Comment by tk315** [comment]
Please review sir @HarshCasper @iamrajiv @ankitaggarwal23 @atarax665 @gat786 @nidh-ish

**Review by iamrajiv — APPROVED** [review]

**Comment by tk315** [comment]
@HarshCasper Build done successfully

**Comment by tk315** [comment]
@vybhav72954 please review

**Comment by tk315** [comment]
@siddharth25pandey please review

**Comment by tk315** [comment]
@atarax665 please review

**Review by atarax665 — APPROVED** [review]

**Comment by atarax665** [comment]
Resolve conflict so that I can merge the PR.

**Review by ankitaggarwal23 — APPROVED** [review]
LGTM💯

**Pull request merged**
