### PR TITLE
perfect cube added

### LINKED ISSUE #360: Article on Perfect Cube
## 🚀 Feature

I would like to add an article for finding whether the number is perfect cube or not.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

### PR DESCRIPTION
**Pull request by shivammahajancse**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #360

### CODE REVIEW

**Comment by shivammahajancse** [comment]
please review @siddharth25pandey @atarax665 @iamrajiv sir

**Review by iamrajiv — APPROVED** [review]

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@shivammahajancse Resolve the merge Conflicts

**Comment by shivammahajancse** [comment]
@siddharth25pandey conflict done sir

**Comment by shivammahajancse** [comment]
@siddharth25pandey sir conflict solved

**Review by siddharth25pandey — APPROVED** [review]
@shivammahajancse LGTM, Able to merge, now

**Pull request merged**
