### PR TITLE
Reverse a Number

### PR DESCRIPTION
**Pull request by tk315**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

reverse a number article added

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#82

### CODE REVIEW

**Comment by tk315** [comment]
Please review @ankitaggarwal23 @HarshCasper @iamrajiv

**Comment by tk315** [comment]
Please review @ankitaggarwal23 @HarshCasper @iamrajiv @atarax665

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Make the same changes I asked here: https://github.com/TesseractCoding/NeoAlgo-Docs/pull/176

**Review by iamrajiv — APPROVED** [review]

**Comment by tk315** [comment]
Please review @HarshCasper @ankitaggarwal23 @iamrajiv

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
