### PR TITLE
snake traversal added

### LINKED ISSUE #349: Print Matrix in snake pattern
## 🚀 Feature

An article on printing matrix in snake pattern

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by tk315**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

# Both code in C++ and Python is added by me

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #349

### CODE REVIEW

**Comment by tk315** [comment]
Please review sir @HarshCasper @iamrajiv @ankitaggarwal23 @atarax665 @gat786 @nidh-ish

**Review by iamrajiv — APPROVED** [review]

**Comment by tk315** [comment]
@HarshCasper Build Done Successfully

**Review by shivammahajancse — APPROVED** [review]

**Comment by tk315** [comment]
@vybhav72954 please review

**Comment by tk315** [comment]
@siddharth25pandey please review

**Comment by tk315** [comment]
@atarax665 please review

**Review by ankitaggarwal23 — APPROVED** [review]

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by tk315** [comment]
@ankitaggarwal23 Done

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
