### PR TITLE
Insertion Sort in Java

### LINKED ISSUE #478: Add Java code for Insertion Sort
## 💥 Proposal

I would like to add a Java code to 'Insertion Sort' under 'Sorting Algorithms'.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

### PR DESCRIPTION
**Pull request by apoorva0107**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added Java code for "Insertion Sort" under "Sorting Algorithms"

### Checklist

- [✔️] I've read the contribution guidelines.
- [✔️] I've checked the issue list before deciding what to submit.
- [✔️] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixes #478

### CODE REVIEW

**Comment by apoorva0107** [comment]
@HarshCasper @iamrajiv please review my PR

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@apoorva0107 Please refactored the docs the tests are failing.

**Comment by apoorva0107** [comment]
@iamrajiv @ankitaggarwal23 Please guide me through it

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@apoorva0107 You have to edit the `sidebars.js ` file. Please refer to other PR to get an overview. Also, I don't think the `linear-search.mdx ` file belongs to this PR.

**Comment by apoorva0107** [comment]
@iamrajiv how to resolve merge conflict?

**Review by ankitaggarwal23 — COMMENTED** [review]
Branch issue from your side.

**Pull request closed without merging**
