### PR TITLE
Add a GH Action to test the Application Build

### PR DESCRIPTION
**Pull request by rubyruins**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Adds a Github workflow that performs the following steps on every push or pull:
- Checks cache for dependencies
- Installs the required dependencies
- Creates a build

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4

### CODE REVIEW

**Review by vybhav72954 — APPROVED** [review]
@HarshCasper LGTM

**Comment by HarshCasper** [comment]
Thanks @rubyruins :)

**Comment by rubyruins** [comment]
@HarshCasper 😊

**Comment by rubyruins** [comment]
Hi @HarshCasper, I was just wondering - once the code is merged, does Github auto mark the issue as closed? Just curious since the issue hasn't closed itself 😅

**Comment by HarshCasper** [comment]
> Hi @HarshCasper, I was just wondering - once the code is merged, does Github auto mark the issue as closed? Just curious since the issue hasn't closed itself  I forgot to add the 'Fixes #' when referencing it in the PR!

It should. But sometimes it doesn't work. Nevertheless I have closed the Issue and your action is working flawlessly

**Comment by vybhav72954** [comment]
> Hi @HarshCasper, I was just wondering - once the code is merged, does Github auto mark the issue as closed? Just curious since the issue hasn't closed itself 😅 I forgot to add the 'Fixes #' when referencing it in the PR!

That's because the body was edited after the PR was merged! At the time of merging it only had #4 in the body.

**Comment by rubyruins** [comment]
@HarshCasper, thanks for checking! @vybhav72954, yes, I think you're right. I added it as soon as I remembered,but anyways it is merged successfully now 😅

**Pull request merged**
