### PR TITLE
java code added for counting sort

### PR DESCRIPTION
**Pull request by anshmishra010**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added java code in counting sort

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#50

### CODE REVIEW

**Comment by anshmishra010** [comment]
@atarax665 @bhav09 @ankitaggarwal23 
please check and let me know what I can do from my end

**Comment by anshmishra010** [comment]
@bhav09  @gat786  @ankitaggarwal23 @iamrajiv  @HarshCasper 
It's been more than 3 days , I have also sent the link in the discord .
If there is any issue with this code then please let me know so that I can contribute to more codes in Docs .

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@anshmishra010 Please refactored the docs the tests are failing.

**Comment by anshmishra010** [comment]
@iamrajiv I also know the test are failing , that why I asked you mentors to help me as I was unable to decode the issue

**Comment by anshmishra010** [comment]
@iamrajiv so if possible please help me

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@anshmishra010 You have to edit the `sidebars.js ` file. Please refer to other PR to get an overview.

**Comment by anshmishra010** [comment]
Screenshot (178)

**Comment by anshmishra010** [comment]
See in side bar.js . 
The file is present named using counting sort 
@iamrajiv

**Comment by anshmishra010** [comment]
As I have only added a  java code into the pre existing code , so can you just tell where in sidebar.js should I write

**Comment by anshmishra010** [comment]
@iamrajiv  done , with fixes

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@anshmishra010 
The basic layout for the article should be:

Introduction
Explanation
Algorithm
Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
Sample I/O
Complexity Analysis

**Comment by anshmishra010** [comment]
Okay so I have to put java code above the python ?
@siddharth25pandey

**Review by bhav09 — CHANGES_REQUESTED** [review]
You need to write the algorithm, it's working and need to comment on the code a little more.
Also mention, the complexity and auxiliary space if any.

**Comment by anshmishra010** [comment]
@bhav09 
check now as I have added some more comments

**Comment by anshmishra010** [comment]
Screenshot (179)


Whereas the complexity analysis remains the same @bhav09

**Comment by anshmishra010** [comment]
@bhav09  I have added the algorithm in the code do checkout 
@siddharth25pandey @ankitaggarwal23

**Comment by anshmishra010** [comment]
@siddharth25pandey 
Can you view my other pr too ?
And one doubt , as in docs every gets level 3 ?

**Comment by siddharth25pandey** [comment]
Dear @anshmishra010. You have just modified the doc by adding the C++ code, So it's far sufficient to give Label 2 Points to this PR. For other PR DM me on the discord or tag me in the channel itself

**Comment by anshmishra010** [comment]
Okay thankyou for clearing the doubt !
@siddharth25pandey

**Comment by anshmishra010** [comment]
I have sent u @siddharth25pandey

**Comment by anshmishra010** [comment]
@siddharth25pandey Please change the level

**Pull request merged**
